name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.10-slim
    env:
      ARQ_BACKEND: redis://redis:6379/0
      SQLALCHEMY_DATABASE_URI: postgresql+asyncpg://postgres:password@postgres:5432/postgres

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir pipenv==2021.11.23
        pipenv install --dev --system
    - name: Lint
      run: cd src && flake8 .
    - name: Test
      run: cd src && pytest
